apiVersion: v1
kind: Service
metadata:
  name: rick-morty-service
spec:
  selector:
    app: rick-morty
  type: {{ .Values.service.type }}  # לוקח מ-values.yaml (ClusterIP)
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }} # פורט 80
      targetPort: {{ .Values.service.targetPort }} # פורט 8080
