# מספר הרפליקות (הפודים)
replicaCount: 1

# הגדרות האימג'
image:
  # שינוי 1: השם המלא של האימג' בדוקר האב (כולל השם משתמש שלך)
  repository: bendagan/rick-and-morty-app
  
  tag: "latest"
  
  # שינוי 2: חובה לשנות ל-Always כדי שהוא יחפש עדכונים באינטרנט
  pullPolicy: Always

# הגדרות הסרוויס
service:
  type: NodePort
  port: 80
  targetPort: 8080

# הגדרות ה-Ingress
ingress:
  enabled: true
  host: rick-morty.local
